macmenu File.Print key=<nop>
set guifont=Inconsolata-dz\ for\ Powerline:h12
" set guifont=Monaco\ for\ Powerline:h12
set gcr=n:blinkon0
set guioptions-=rL

highlight DiffAdd guibg=#859900 guifg=bg
highlight DiffDelete guibg=#dc322f guifg=bg
highlight DiffChange guibg=#b58900 guifg=bg
highlight DiffText guibg=#268bd2 guifg=bg
