call plug#begin('~/.config/nvim/bundle')

" General
Plug 'Shougo/vimproc.vim', {'do': 'make'}
Plug 'Shougo/unite.vim'
Plug 'Shougo/unite-outline'
Plug 'bling/vim-airline'
Plug 'osyo-manga/unite-quickfix'
Plug 'tpope/vim-repeat'
Plug 'benekastah/neomake'

" Code browsing
" Plug 'kien/ctrlp.vim'
Plug 'rking/ag.vim'

" Editing
Plug 'wellle/targets.vim'
Plug 'terryma/vim-multiple-cursors'
Plug 'tpope/vim-surround'

" Git
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'

" Navigation
Plug 'easymotion/vim-easymotion'
Plug 'myusuf3/numbers.vim'
Plug 'kshenoy/vim-signature'

" Code complete
Plug 'Valloric/YouCompleteMe', {'do': './install.py --clang-completer'}

" Plug 'critiqjo/lldb.nvim'
" Plug 'sjl/vitality.vim'

Plug 'tomtom/tcomment_vim'
Plug 'octol/vim-cpp-enhanced-highlight'
Plug 'bronson/vim-trailing-whitespace'
" Plug 'xolox/vim-misc'
" Plug 'xolox/vim-easytags'

" Latex
" Plug 'LaTeX-Box-Team/LaTeX-Box'

" color themes
Plug 'morhetz/gruvbox'

" Plug finalization
call plug#end()

" Set colorscheme
let $NVIM_TUI_ENABLE_TRUE_COLOR=1
if !has("gui_running")
  set background=dark
endif
colorscheme gruvbox

" General
set exrc
set secure
set autoread
set updatetime=500
set encoding=utf-8
set termencoding=utf-8
set formatoptions+=j
set mouse=nicr
nnoremap <Space> <nop>
let mapleader=' '

" Indentation
set autoindent
set smarttab
set tabstop=2 shiftwidth=2 expandtab
set shiftround
set nostartofline
set backspace=indent,eol,start

" Completion
set complete-=i
set completeopt=menuone,longest,preview
set wildmenu

set nrformats-=octal
set scrolloff=2

" Search
set incsearch
set hlsearch
set ignorecase
set smartcase
" Use <C-L> to clear the highlighting of :set hlsearch
if maparg('<C-L>', 'n') ==# ''
  nnoremap <silent> <C-L> :nohlsearch<CR><C-L>
endif

" Display
set laststatus=2
set ruler
set cursorline      " highlight the current line
set number          " show the line numbers
set showcmd
set showmatch
set showmode
set list
set listchars=tab:»·

" Folding
set foldmethod=syntax
set foldlevelstart=20

" Disable all backup files
set nobackup
set nowritebackup
set noswapfile

" " display preview windows at the bottom
" autocmd WinEnter * if &previewwindow | wincmd J | endif

" argdo wrapper that will disable all events for read/save
command! -nargs=? Argdo call Argdo(<q-args>)
function! Argdo(command)
  set eventignore=all
  execute 'argdo '. a:command
 " . ' | update'
  set eventignore=
endfunction

"
" Plugins config
"

" Unite
let g:unite_prompt = "➤  "
" let g:unite_enable_start_insert = 1
" let g:unite_split_rule = "botright"
let g:unite_source_history_yank_enable = 1
let g:unite_source_grep_command = 'ag'
let g:unite_source_grep_default_opts =
      \ '--line-numbers --nocolor --nogroup --hidden'
call unite#custom_source('file_rec,file_rec/async,file_mru,file,buffer,grep',
      \ 'ignore_pattern', join([
      \ 'build/'
      \ ], '\|'))
nnoremap <silent> <C-P> :<C-u>Unite -start-insert -buffer-name=files buffer file_rec/async:!<CR>
nnoremap <silent> <leader>/ :<C-u>Unite -start-insert -buffer-name=line -custom-line-enable-highlight line<CR>
nnoremap <silent> <leader>o :<C-u>Unite -start-insert -buffer-name=outline -vertical outline<CR>
nnoremap <silent> <leader>a :<C-u>Unite -start-insert -buffer-name=grep grep:.<CR>
nnoremap <silent> <leader>q :<C-u>Unite -start-insert -buffer-name=quickfix quickfix<CR>
nnoremap <silent> <leader>r :<C-u>UniteResume<CR>

" Ultisnip
" NOTE: <f1> otherwise it overrides <tab> forever
let g:UltiSnipsExpandTrigger="<M-tab>"
let g:UltiSnipsJumpForwardTrigger="<M-tab>"
let g:UltiSnipsJumpBackwardTrigger="<M-S-tab>"
let g:did_UltiSnips_vim_after = 1

" vim-airline
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1

" Easymotion
map <Leader> <Plug>(easymotion-prefix)

" YouCompleteMe
let g:ycm_key_list_select_completion=['<Tab>', '<Down>']
let g:ycm_key_list_previous_completion=['<S-Tab>', '<Up>']
let g:ycm_error_symbol = 'X'
let g:ycm_warning_symbol = '!'
nnoremap <CR> :YcmCompleter GoTo<CR>
nnoremap <leader>cD :YcmDiags<CR>
nnoremap <leader>ct :YcmCompleter GetType<CR>
nnoremap <leader>cd :YcmCompleter GetDoc<CR>

" multiple-cursors
" prevent cursor events from flooding
function Multiple_cursors_before()
  let s:old_ycm_whitelist = g:ycm_filetype_whitelist
  let g:ycm_filetype_whitelist = {}
endfunction

function Multiple_cursors_after()
  let g:ycm_filetype_whitelist = s:old_ycm_whitelist
endfunction

" Pyclewn
let g:pyclewn_python = "/usr/local/bin/python"

" trailing-whitespace
let g:extra_whitespace_ignored_filetypes = ['unite']

" git-gutter
let g:gitgutter_sign_column_always = 1
" call gitgutter#highlight#define_highlights()
